name: Compile snapshot with Maven

on:
  push:
    branches-ignore:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build snapshot with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload build artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bedwars-plugin-ci-${{ github.run_number }}
          path: bedwars-plugin/target/bedwars-plugin-*.jar
          if-no-files-found: warn
          retention-days: 14
